# -*- coding: utf-8 -*-
"""day2_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jf_3EpmOnd9YdfblSg52WyVDBiyfKysP
"""

n = int(input("Please enter a single digit integer: "))

evens = list(range(n+1))

print(evens[::2])