# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vKJ3cd48YKf6r9ybCwdfdd1adHdg6jdp
"""

list = [1,2,3,"a","b","c"]
print(list)
n = len(list)
list1 = list[:n//2]
list2 = list[n//2:]
list = list2 + list1
print(list)