# -*- coding: utf-8 -*-
"""Day_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T48ur8n7fcW4VNrfizOSyJaE4B_ifdmI
"""

userName = "user"
password = "1234"

log_id = input("Please enter your username: ")
log_pass = input("Please enter your password: ")

if log_id != userName and log_pass == password:
  print("Invalid username, try again!")
elif log_id == userName and log_pass != password:
  print("Invalid password, try again!")
elif log_id != userName and log_pass != password:
  print("Invalid username and password, try again!")
else:
  print("Login successful")